---
- name: Configurations VyOS for 1-VARIANT
  hosts: vyos-1var
  gather_facts: no 

  tasks:
    - name: Set "hostname" and "dns"
      vyos.vyos.vyos_config:
        lines:
          - set system host-name FW
          - set system name-server 77.88.8.8

    - name: Set address for Main/Remote-Office
      vyos.vyos.vyos_config:
        lines:
          - set interfaces ethernet eth1 description "Main-Office"
          - set interfaces ethernet eth2 description "Remote-Office"
          - set interfaces ethernet eth1 address 172.16.112.1/20
          - set interfaces ethernet eth2 address 192.168.100.1/24

    - name: Configurations NAT for Main-Office
      vyos.vyos.vyos_config:
        lines:
          - set nat source rule 172 outbound-interface eth0
          - set nat source rule 172 source address "172.16.112.0/20"
          - set nat source rule 172 translation address masquerade

    - name: Configurations NAT for Remote-Office
      vyos.vyos.vyos_config:
        lines:
          - set nat source rule 192 outbound-interface eth0
          - set nat source rule 192 source address "192.168.100.0/24"
          - set nat source rule 192 translation address masquerade

- name: Configurations VyOS for 2-VARIANT
  hosts: vyos-2var
  gather_facts: no 

  tasks:
    - name: Set "hostname" and "dns"
      vyos.vyos.vyos_config:
        lines:
          - set system host-name FW
          - set system name-server 77.88.8.8

    - name: Set address for Main/Remote-Office
      vyos.vyos.vyos_config:
        lines:
          - set interfaces ethernet eth1 description "Main-Office"
          - set interfaces ethernet eth2 description "Remote-Office"
          - set interfaces ethernet eth1 address 172.16.112.1/20
          - set interfaces ethernet eth2 address 10.10.10.1/24

    - name: Configurations NAT for Main-Office
      vyos.vyos.vyos_config:
        lines:
          - set nat source rule 172 outbound-interface eth0
          - set nat source rule 172 source address "172.16.112.0/20"
          - set nat source rule 172 translation address masquerade

    - name: Configurations NAT for Remote-Office
      vyos.vyos.vyos_config:
        lines:
          - set nat source rule 10 outbound-interface eth0
          - set nat source rule 10 source address "10.10.10.0/24"
          - set nat source rule 10 translation address masquerade
